language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: clickerr
  api_key:
    secure: JB7v91+0xmYu9tLlL2XK1PJhzV5Xkq3jvxwN62uqkgr+CSjZRUyiuvCxW4JBafRelop8gMhDyro5XyYftLtvV0/lKsdHZ+96OwYtbmhBdMJH3puXpow/LJmz0quSp+lkSOqAUWGYH5gV4wo+Bo1UXy1fHkiAnEPdaK7Ki8jWi4l603wwtXEvdY7rWNcBgU2s72iEKU14LddgQYywpKAQQPDCwUidjtQYZcCG1XA8bqIFecO7LABfPSiIEuevoahHm40aU/kMd2ulKAKwjEG4e97HEs00qB9mqqBCo5BdWfu2nCFwLVPM0x/i9Z817bKYqkbuTKmKv1dXiXj87Al1TBpj6gzQ71pnz07qxLnRx0UYz0dYxwmPIczRfRnJb+k+GOD5h63sXzr7iZZzkOgAN/DXNwIegaXaXJJd8CQkNZMlzYdH/TCgAaGmdhNzcuChzGgBPrDIfLXlE4rnn1fkHFROxex2AvnmurOEnMoo9SwGrnEOsF6hwLddok+3f5gFPdz66dDJ/CLBE7SRGqsn5DDjRi5+ivuM2DX746RbkQvYxhhHUkfKH8NqFR3lc4oOI3MTSK5fH+fy31jk637PQqDSvMuIs17FX5RPTz+iNQ2mwoUOJu4M89KUt114E5GPrJ1LBE7U9O08H7y8gdKIG+OCu4E83QezQwOxo8nBxOc=
